
// category
export const CATEGORY_DELETE_START = 'CATEGORY_DELETE_START';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_DELETE_FAILED = 'CATEGORY_DELETE_FAILED';
export const CATEGORY_DELETE = 'CATEGORY_DELETE';

export const CATEGORY_UPDATE_START = 'CATEGORY_UPDATE_START';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_UPDATE_FAILED = 'CATEGORY_UPDATE_FAILED';
export const CATEGORY_UPDATE = 'CATEGORY_UPDATE';

export const CATEGORY_CREATE_START = 'CATEGORY_CREATE_START';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_CREATE_FAILED = 'CATEGORY_CREATE_FAILED';
export const CATEGORY_CREATE = 'CATEGORY_CREATE';

// customer 

export const CUSTOMER_GET_LIST_START = 'CUSTOMER_GET_LIST_START';
export const CUSTOMER_GET_LIST_SUCCESS = 'CUSTOMER_GET_LIST_SUCCESS';
export const CUSTOMER_GET_LIST_FAILED = 'CUSTOMER_GET_LIST_FAILED';
export const CUSTOMER_GET_LIST = 'CUSTOMER_GET_LIST';

export const CUSTOMER_GET_DETAIL_START = 'CUSTOMER_GET_DETAIL_START';
export const CUSTOMER_GET_DETAIL_SUCCESS = 'CUSTOMER_GET_DETAIL_SUCCESS';
export const CUSTOMER_GET_DETAIL_FAILED = 'CUSTOMER_GET_DETAIL_FAILED';
export const CUSTOMER_GET_DETAIL = 'CUSTOMER_GET_DETAIL';

// product

export const PRODUCT_DELETE_START = 'PRODUCT_DELETE_START';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAILED = 'PRODUCT_DELETE_FAILED';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';

export const PRODUCT_UPDATE_START = 'PRODUCT_UPDATE_START';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATE_FAILED = 'PRODUCT_UPDATE_FAILED';
export const PRODUCT_UPDATE = 'PRODUCT_UPDATE';

export const PRODUCT_CREATE_START = 'PRODUCT_CREATE_START';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_CREATE_FAILED = 'PRODUCT_CREATE_FAILED';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';