// sagas action types

// auth
export const AUTH_REGISTER_START = 'AUTH_REGISTER_START';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILED = 'AUTH_REGISTER_FAILED';
export const AUTH_REGISTER = 'AUTH_REGISTER';

export const AUTH_LOGIN_START = 'AUTH_LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

// profile

export const PROFILE_GET_START = 'PROFILE_GET_START';
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';
export const PROFILE_GET_FAILED = 'PROFILE_GET_FAILED';
export const PROFILE_GET = 'PROFILE_GET';

export const PROFILE_UPDATE_START = 'PROFILE_UPDATE_START';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILED = 'PROFILE_UPDATE_FAILED';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';

export const CATEGORY_LIST_GET_START = 'CATEGORY_LIST_GET_START';
export const CATEGORY_LIST_GET_SUCCESS = 'CATEGORY_LIST_GET_SUCCESS';
export const CATEGORY_LIST_GET_FAILED = 'CATEGORY_LIST_GET_FAILED';
export const CATEGORY_LIST_GET = 'CATEGORY_LIST_GET';

export const CATEGORY_GET_DETAIL_START = 'CATEGORY_GET_DETAIL_START';
export const CATEGORY_GET_DETAIL_SUCCESS = 'CATEGORY_GET_DETAIL_SUCCESS';
export const CATEGORY_GET_DETAIL_FAILED = 'CATEGORY_GET_DETAIL_FAILED';
export const CATEGORY_GET_DETAIL = 'CATEGORY_GET_DETAIL';

// product

export const PRODUCT_LIST_GET_START = 'PRODUCT_LIST_GET_START';
export const PRODUCT_LIST_GET_SUCCESS = 'PRODUCT_LIST_GET_SUCCESS';
export const PRODUCT_LIST_GET_FAILED = 'PRODUCT_LIST_GET_FAILED';
export const PRODUCT_LIST_GET = 'PRODUCT_LIST_GET';

export const PRODUCT_DETAIL_GET_START = 'PRODUCT_DETAIL_GET_START';
export const PRODUCT_DETAIL_GET_SUCCESS = 'PRODUCT_DETAIL_GET_SUCCESS';
export const PRODUCT_DETAIL_GET_FAILED = 'PRODUCT_DETAIL_GET_FAILED';
export const PRODUCT_DETAIL_GET = 'PRODUCT_DETAIL_GET';