export const VENDOR_GET_PRODUCT_LIST = 'VENDOR_GET_PRODUCT_LIST';
export const VENDOR_GET_PRODUCT_LIST_START = 'VENDOR_GET_PRODUCT_LIST_START';
export const VENDOR_GET_PRODUCT_LIST_SUCCESS = 'VENDOR_GET_PRODUCT_LIST_SUCCESS';
export const VENDOR_GET_PRODUCT_LIST_FAILED = 'VENDOR_GET_PRODUCT_LIST_FAILED';

export const VENDOR_GET_ORDER_LIST = 'VENDOR_GET_ORDER_LIST';
export const VENDOR_GET_ORDER_LIST_START = 'VENDOR_GET_ORDER_LIST_START';
export const VENDOR_GET_ORDER_LIST_SUCCESS = 'VENDOR_GET_ORDER_LIST_SUCCESS';
export const VENDOR_GET_ORDER_LIST_FAILED = 'VENDOR_GET_ORDER_LIST_FAILED';

export const VENDOR_CREATE_PRODUCT = 'VENDOR_CREATE_PRODUCT';
export const VENDOR_CREATE_PRODUCT_START = 'VENDOR_CREATE_PRODUCT_START';
export const VENDOR_CREATE_PRODUCT_SUCCESS = 'VENDOR_CREATE_PRODUCT_SUCCESS';
export const VENDOR_CREATE_PRODUCT_FAILED = 'VENDOR_CREATE_PRODUCT_FAILED';